nama = input("Masukkan Nama Anda :   ")
nim = input("Masukkan NIM Anda  :   ")
print("\n Welcome ", nama)
print("Your NIM is ", nim)

print("\nQuestion1")
print("Diketahui sisi = 6, sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun1 = input("Nama Bangun Datar  =   ")
x = float(input("Sisi :   "))
y = float(input("Sisi :   "))
print("Bangun datar tersebut adalah ", bangun1, "dan Luas Bangun Datar Tersebut adalah ", x * y)

print("\nQuestion 2")
print("Diketahui alas = 7, tinggi = 8, Sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun2 = input("Nama Bangun Datar  =   ")
x = float(input("alas   :   "))
y = float(input("tinggi :   "))
z = float("0.5")
print("Bangun datar tersebut adalah ", bangun2, "dan Luas Bangun Datar Tersebut adalah ", x * z * y)

print("\nQuestion 3")
print("Diketahui Panjang = 4, Lebar = 9, Sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun3 = input("Nama Bangun Datar  =   ")
x = float(input("Panjang :   "))
y = float(input("Lebar   :   "))
print("Bangun datar tersebut adalah ", bangun3, "dan Luas Bangun Datar Tersebut adalah ", x * y)

print("\nQuestion 4")
print("Diketahui Jari-jari = 56, Sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun4 = input("Nama Bangun Datar  =   ")
x = float(input("Jari-jari  :   "))
z = x
print("Bangun datar tersebut adalah ", bangun4, "dan Luas Bangun Datar Tersebut adalah ", 3.14 * (x * z))

print("\nQuestion 5")
print("Diketahui Diagonal I = 4, Diagonal II = 8, Sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun5 = input("Nama Bangun Datar  =   ")
x = float(input("Diagonal I  :   "))
y = float(input("Diagonal II :   "))
print("Bangun datar tersebut adalah ", bangun5, "dan Luas Bangun Datar Tersebut adalah ", (0.5 * x) * y)

print("\nQuestion 6")
print("Diketahui Sisi AB dan CD sejajar, Sisi AB = 6, Sisi CD = 8, Tinggi = 3, Sebutkan Nama dan Hitunglah Luas Bangun Datar Tersebut!")
bangun6 = input("Nama Bangun Datar  =   ")
x = float(input("Sisi AB    :   "))
y = float(input("Sisi CD    :   "))
t = float(input("Tinggi     :   "))
print("Bangun datar tersebut adalah ", bangun6, "dan Luas Bangun Datar Tersebut adalah ", 0.5 * t * (x + y))

print("\nQuestion 7")
print("Diketahui Sebuah Jajar Genjang dengan Alas = 9, Tinggi = 7, Hitunglah Luas Bangun Datar Tersebut!")
bangun7 = "Jajar Genjang"
x = float(input("Alas   :   "))
y = float(input("Tinggi :   "))
print("Bangun datar tersebut adalah ", bangun7, "dan Luas Bangun Datar Tersebut adalah ", x * y)